# Pre-commit hooks configuration
# Install: uv tool install pre-commit pre-commit-uv
# Setup: pre-commit install
#
# IMPORTANT: These hooks use the EXACT same commands as manual runs
# to ensure consistency with pyproject.toml settings

repos:
  # uv-specific hooks
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.11
    hooks:
      - id: uv-lock

  # Run checks in the same order as CI and manual commands
  # All use 'local' repo to ensure we use exact commands with pyproject.toml settings
  - repo: local
    hooks:
      # 1. Type checking with ty (first)
      - id: ty-check
        name: Type check with ty
        entry: uv run ty check src
        language: system
        pass_filenames: false
        always_run: true

      # 2. Linting with ruff (second) - auto-fixes safe issues
      - id: ruff-check
        name: Lint with ruff
        entry: uv run ruff check src --fix
        language: system
        pass_filenames: false
        always_run: true

      # 3. Formatting with ruff (third) - auto-applies fixes
      - id: ruff-format
        name: Format with ruff
        entry: uv run ruff format src
        language: system
        pass_filenames: false
        always_run: true

  # Minimal but useful file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml        # Validate YAML syntax
      - id: check-json        # Validate JSON syntax
      - id: check-toml        # Validate TOML syntax (pyproject.toml)
      - id: check-merge-conflict  # Prevent committing merge markers
