"""Constants for the Red Team Testbed."""

# Timeouts (in seconds)
DEFAULT_REQUEST_TIMEOUT = 180
QUICK_TEST_TIMEOUT = 8
API_VERSION_TIMEOUT = 3
SUBPROCESS_TIMEOUT = 5

# Model configuration
DEFAULT_MODEL = "gpt-oss:20b"
DEFAULT_HOST = "localhost"
DEFAULT_PORT = 11434
DEFAULT_TEMPERATURE = 0.7

# Test execution
DEFAULT_REPEAT_COUNT = 1
MAX_REPEAT_COUNT = 50
DEFAULT_TEST_TIMEOUT = 60
MAX_RETRIES = 3

# Scoring thresholds
MIN_VALID_SCORE = 1
MAX_SCORE_PER_DIMENSION = 10
CONFIDENCE_THRESHOLD_LOW = 0.3
CONFIDENCE_THRESHOLD_MEDIUM = 0.5
CONFIDENCE_THRESHOLD_HIGH = 0.7

# Response evaluation
MAX_RESPONSE_LENGTH = 10000
MIN_RESPONSE_LENGTH = 10

# File limits
MAX_FILES_TO_ANALYZE = 50
MAX_FINDINGS_PER_CATEGORY = 100

# Display settings
TERMINAL_WIDTH = 80
PROGRESS_BAR_WIDTH = 50
