name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml
      
      - name: Install dependencies
        run: uv sync
      
      - name: Type check with ty
        run: uv run ty check src
      
      - name: Lint with ruff
        run: uv run ruff check src
      
      - name: Format check with ruff
        run: uv run ruff format --check src