name: Lint and Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - uses: astral-sh/setup-uv@v4
      
      - run: uv sync --dev
      
      - run: uv run ruff format src --check
        
      - run: uv run ruff check src
      
      - run: uv run ty check src